Fix narrowing conversion error
Fixes #2.

Explicitly cast values to `DTsucc` to avoid error:
```
static/suffixtree/RMQ_succinct.cpp:115:85: error: narrowing conversion of ‘-1’ from ‘int’ to ‘DTsucc {aka unsigned char}’ inside { } [-Wnarrowing]
  const DTsucc RMQ_succinct::HighestBitsSet[8] = {~0, ~1, ~3, ~7, ~15, ~31, ~63, ~127};
```

This appears to be an error in C++11 and newer, which is typically
the default mode these days.